#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
HOME_OVERRIDE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --home)
      HOME_OVERRIDE="${2:-}"
      shift 2
      ;;
    --help|-h)
      cat <<'EOF'
Usage: ./bootstrap.sh [--home PATH]
EOF
      exit 0
      ;;
    *)
      echo "bootstrap: unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

# shellcheck source=/dev/null
source "$ROOT/scripts/local_env.sh"
if [ -n "$HOME_OVERRIDE" ]; then
  export MADONGMEI_HOME="$HOME_OVERRIDE"
fi
madongmei_export_runtime_env

umask 077
mkdir -p \
  "$CODEX_HOME" \
  "$MADONGMEI_HOME" \
  "$MADONGMEI_DATA_DIR" \
  "$MADONGMEI_LOG_DIR" \
  "$MADONGMEI_CACHE_DIR" \
  "$MADONGMEI_BRIDGE_ROOT" \
  "$WORKSPACE_SOURCE_ROOT" \
  "$WORKSPACE_SOURCE_LINK" \
  "$MEMORY_RUNTIME_DIR" \
  "$MADONGMEI_GRAPH_DIR" \
  "$MADONGMEI_GRAPH_SNAPSHOT_DIR" \
  "$(dirname "$WORKSPACE_REGISTRY_FILE")"
mkdir -p "$MADONGMEI_WIKI_DIR" "$MADONGMEI_SKILL_DIR"
touch "$MADONGMEI_DB_PATH"
touch "$MADONGMEI_GRAPH_DB_PATH"
touch "$WORKSPACE_REGISTRY_FILE"

CONFIG_FILE="$MADONGMEI_HOME/config.env"
if [ ! -f "$CONFIG_FILE" ]; then
  cat >"$CONFIG_FILE" <<EOF
# Generated by bootstrap.sh
export CODEX_HOME="$CODEX_HOME"
export MADONGMEI_HOME="$MADONGMEI_HOME"
export MADONGMEI_DATA_DIR="$MADONGMEI_DATA_DIR"
export MADONGMEI_LOG_DIR="$MADONGMEI_LOG_DIR"
export MADONGMEI_CACHE_DIR="$MADONGMEI_CACHE_DIR"
export MADONGMEI_DB_PATH="$MADONGMEI_DB_PATH"
export MADONGMEI_BRIDGE_ROOT="$MADONGMEI_BRIDGE_ROOT"
export WORKSPACE_SOURCE_ROOT="$WORKSPACE_SOURCE_ROOT"
export WORKSPACE_SOURCE_LINK="$WORKSPACE_SOURCE_LINK"
export WORKSPACE_ROOT="$WORKSPACE_ROOT"
export MEMORY_RUNTIME_DIR="$MEMORY_RUNTIME_DIR"
export WORKSPACE_REGISTRY_FILE="$WORKSPACE_REGISTRY_FILE"
export MADONGMEI_GRAPH_DIR="$MADONGMEI_GRAPH_DIR"
export MADONGMEI_GRAPH_RUNTIME_DIR="$MADONGMEI_GRAPH_RUNTIME_DIR"
export MADONGMEI_GRAPH_DB_PATH="$MADONGMEI_GRAPH_DB_PATH"
export MADONGMEI_GRAPH_SNAPSHOT_DIR="$MADONGMEI_GRAPH_SNAPSHOT_DIR"
export MADONGMEI_WIKI_DIR="$MADONGMEI_WIKI_DIR"
export MADONGMEI_SKILL_DIR="$MADONGMEI_SKILL_DIR"
EOF
fi

printf 'bootstrap: home=%s\n' "$MADONGMEI_HOME"
printf 'bootstrap: codex_home=%s\n' "$CODEX_HOME"
printf 'bootstrap: bridge_root=%s\n' "$MADONGMEI_BRIDGE_ROOT"
printf 'bootstrap: workspace_root=%s\n' "$WORKSPACE_SOURCE_ROOT"
printf 'bootstrap: workspace_link=%s\n' "$WORKSPACE_SOURCE_LINK"
printf 'bootstrap: memory_runtime=%s\n' "$MEMORY_RUNTIME_DIR"
printf 'bootstrap: db=%s\n' "$MADONGMEI_DB_PATH"
printf 'bootstrap: graph_db=%s\n' "$MADONGMEI_GRAPH_DB_PATH"
printf 'bootstrap: wiki=%s\n' "$MADONGMEI_WIKI_DIR"
printf 'bootstrap: skill=%s\n' "$MADONGMEI_SKILL_DIR"
printf 'bootstrap: config=%s\n' "$CONFIG_FILE"
